/*
 * The AGPL License (AGPL)
 * Copyright (c) 2023 hans000
 */

export const KeybindList = [
    { id: 'key.jump', name: '', en: 'Jump' },
    { id: 'key.sneak', name: '', en: 'Sneak' },
    { id: 'key.sprint', name: '', en: 'Sprint' },
    { id: 'key.left', name: '', en: 'Strafe Left' },
    { id: 'key.right', name: '', en: 'Strafe Right' },
    { id: 'key.back', name: '', en: 'Walk Backward' },
    { id: 'key.forward', name: '', en: 'Walk Forward' },
    { id: 'key.attack', name: '', en: 'Attack/Destroy' },
    { id: 'key.pickItem', name: '', en: 'Pick Block' },
    { id: 'key.use', name: '', en: 'Use Item/Place Block' },
    { id: 'key.drop', name: '', en: 'Drop Selected Item' },
    { id: 'key.hotbar.1', name: '', en: 'Hotbar Slot 1' },
    { id: 'key.hotbar.2', name: '', en: 'Hotbar Slot 2' },
    { id: 'key.hotbar.3', name: '', en: 'Hotbar Slot 3' },
    { id: 'key.hotbar.4', name: '', en: 'Hotbar Slot 4' },
    { id: 'key.hotbar.5', name: '', en: 'Hotbar Slot 5' },
    { id: 'key.hotbar.6', name: '', en: 'Hotbar Slot 6' },
    { id: 'key.hotbar.7', name: '', en: 'Hotbar Slot 7' },
    { id: 'key.hotbar.8', name: '', en: 'Hotbar Slot 8' },
    { id: 'key.hotbar.9', name: '', en: 'Hotbar Slot 9' },
    { id: 'key.inventory', name: '', en: 'Open/Close Inventory' },
    { id: 'key.swapOffhand', name: '', en: 'Swap Items In Hands' },
    { id: 'key.loadToolbarActivator', name: '', en: 'Load Toolbar Activator' },
    { id: 'key.saveToolbarActivator', name: '', en: 'Save Toolbar Activator' },
    { id: 'key.playerlist', name: '', en: 'List Players' },
    { id: 'key.chat', name: '', en: 'Open Chat' },
    { id: 'key.command', name: '', en: 'Open Command' },
    { id: 'key.socialInteractions', name: '', en: 'Social Interactions Screen' },
    { id: 'key.advancements', name: '', en: 'Advancements' },
    { id: 'key.spectatorOutlines', name: '', en: 'Highlight Players' },
    { id: 'key.screenshot', name: '', en: 'Take Screenshot' },
    { id: 'key.smoothCamera', name: '', en: 'Toggle Cinematic Camera' },
    { id: 'key.fullscreen', name: '', en: 'Toggle Fullscreen' },
    { id: 'key.togglePerspective', name: '', en: 'Toggle Perspective' },
]